project:
  type: book
  output-dir: docs

book:
  title: "LLM Agentic Systems"
  author: "Calvin Chi"
  date: "7/18/2025"
  chapters:
    - index.qmd
    - part: "Concepts"
      chapters:
        - Introduction.ipynb
        - summary.qmd
        - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



