project:
  type: book
  output-dir: docs

book:
  title: "LLM Agentic Systems"
  author: "Calvin Chi"
  date: "7/18/2025"
  chapters:
    - index.qmd
    - part: "Concepts"
      chapters:
        - introduction.ipynb
        - context.ipynb
        - reflection.ipynb
        - planning.ipynb

format:
  html:
    theme:
      - cosmo
      - brand
    grid:
      body-width: 1800px
  pdf:
    documentclass: scrreprt

bibliography: references.bib
